# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c2a3a8e2-1475-4baf-8d16-ec139608f5d3";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd:3" "noatime" "space_cache=v2" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/c2a3a8e2-1475-4baf-8d16-ec139608f5d3";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd:3" "noatime" "space_cache=v2" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/c2a3a8e2-1475-4baf-8d16-ec139608f5d3";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd:3" "noatime" "space_cache=v2" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/c2a3a8e2-1475-4baf-8d16-ec139608f5d3";
      fsType = "btrfs";
      options = [ "subvol=@swap" "noatime" "space_cache=v2" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1F0E-E0E1";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home/fall_dust/data" = {
    device = "/dev/disk/by-uuid/31fcdaf7-ef08-4782-a498-bb2aeb51dc17";
    fsType = "btrfs";
    options = [ "compress=zstd:3" "noatime" "space_cache=v2" ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp46s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp45s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
